<div id='menu'>

<h1><a href='http://github.com/paranoiq/mantra' id='h1'>Mantra</a> <span class='version'>0.1 alpha</span></h1>


<p>{control dbForm}</p>

<p id='tables'>
{foreach $collList as $collection}
    <a href='{plink Select:default, database=>$presenter->database, collection=>$collection}'>{=t('select')}</a>
    <a href='{plink Collection:default, database=>$presenter->database, collection=>$collection}'>{$collection}</a><br>
{/foreach}
</p>

</div>