{extends @layout.phtml}

{block #title}{$presenter->database}.{$presenter->collection} (mantra){/block}

{block #h2}Collection: {$presenter->collection}{/block}

{block #help}help: <a href='http://www.mongodb.org/display/DOCS/Collections'>Collections</a>, 
    <a href='http://www.mongodb.org/display/DOCS/Indexes'>Indexes</a>{/block}

{block #content}

<p>
<a href='{plink Collection:default}'>Collection</a>
<a href='{plink Select:default}'>Select</a>
<a href='{plink Update:default}'>Update</a>
<a href='{plink Insert:default}'>Insert</a>
<a href='{plink Import:default}'>Import</a>
<a href='{plink RenameColl:default}'>Rename collection</a>
<a href='{plink CreateIndex:default}'>Create index</a>
</p>

{if !empty($info['capped'])}
<p><b>Capped collection:</b>
    <br>- maximal size: {$info['size']|bytes}
    {if !empty($info['max'])}<br>- maximum objects: {$info['max']}{/if}
</p>
{/if}

<h3>Indexes</h3>

{?$form->render('begin')}
{?$form->render('errors')}
<table class='data r4'>
<colgroup span='3' /><colgroup align='right' />
<thead><td></td><th>Name</th><td>Keys</td><td>Size</td></thead>
{foreach $indexes as $index => $info}
    <tr><td>{$form['index'][$info['id']]->control}</td><th>{$index}</th><td>{$info['keys']}</td><td>{$info['size']|bytes:1}</td></tr>
{/foreach}
</table>
<fieldset>
    {$form['drop']->control}
</fieldset>
{?$form->render('end')}

<div style='float: left; margin-right: 2em;'>
<h3>Collection statistics</h3>

<table cellspacing='0' class='info r2'>
<colgroup /><colgroup align='right' />
{foreach $stats as $key => $item}
    <tr>
    {if is_array($item)}
        <th colspan='2'>{$key}</th></tr>
        {foreach $item as $subkey => $subitem}
            <tr><th>{$subkey}</th><td>
            {if is_array($subitem)}
                {foreach $subitem as $subsubkey => $subsubitem}
                    {$subsubkey}: {$subsubitem}<br>
                {/foreach}
            {else}
                {$subitem}
            {/if}
            </td></tr>
        {/foreach}
    {else}
        <th>{$key}</th><td>{$item}</td>
    {/if}
    </tr>
{/foreach}
</table>
</div>

<div>
<h3>Collection usage</h3>

<table cellspacing='0' class='info r2 r3'>
<colgroup /><colgroup span='2' align='right' />
<tr><th>Query</th><th>Time</th><th>Count</th></tr>
{foreach $usage as $key => $item}
    <tr>
        <td>{$key}</td><td>{$item['time']}</td><td>{$item['count']}</td>
    </tr>
{/foreach}
</table>
</div>
