{extends @layout.phtml}

{block #title}{$presenter->database}.{$presenter->collection} (Mantra){/block}

{block #h2}{t}Collection:{/t} {$presenter->collection}{/block}

{block #help}{t}help:{/t} <a href='http://www.mongodb.org/display/DOCS/Collections'>{t}Collections{/t}</a>, 
    <a href='http://www.mongodb.org/display/DOCS/Indexes'>{t}Indexes{/t}</a>{/block}

{block #content}

<p>
<a href='{plink Collection:default}'>{t}Collection{/t}</a>
<a href='{plink Select:default}'>{t}Select{/t}</a>
<a href='{plink Update:default}'>{t}Update{/t}</a>
<a href='{plink Insert:default}'>{t}Insert{/t}</a>
<a href='{plink Import:default}'>{t}Import{/t}</a>
<a href='{plink RenameColl:default}'>{t}Rename collection{/t}</a>
<a href='{plink CreateIndex:default}'>{t}Create index{/t}</a>
</p>

{if !empty($info['capped'])}
<p><b>{t}Capped collection:{/t}</b>
    <br>{t}- maximal size:{/t} {$info['size']|bytes}
    {if !empty($info['max'])}<br>{t}- maximum objects:{/t} {$info['max']}{/if}
</p>
{/if}

<h3>{t}Indexes{/t}</h3>

{?$form->render('begin')}
{?$form->render('errors')}
<table cellspacing='0' class='data r4'>
<colgroup span='3' /><colgroup align='right' />
<thead><td></td><th>{t}Name{/t}</th><td>{t}Keys{/t}</td><td>{t}Size{/t}</td></thead>
{foreach $indexes as $index => $info}
    <tr><td>{$form['index'][$info['id']]->control}</td><th>{$index}</th><td>{$info['keys']}</td><td>{$info['size']|bytes:1}</td></tr>
{/foreach}
</table>
<p>{$form['drop']->control}</p>
{?$form->render('end')}

<div style='float: left; margin-right: 2em;'>
<h3>{t}Collection statistics{/t}</h3>

<table cellspacing='0' class='info r2'>
<colgroup /><colgroup align='right' />
{foreach $stats as $key => $item}
    <tr><th>{$key}</th><td>
    {if in_array($key, array('size', 'avgObjSize', 'storageSize', 'lastExtentSize', 'totalIndexSize'))}
        {$item|bytes}
    {else}
        {$item}
    {/if}
    </td></tr>
{/foreach}
</table>
</div>

<div>
<h3>{t}Collection usage{/t}</h3>

<table cellspacing='0' class='info r2 r3'>
<colgroup /><colgroup span='2' align='right' />
<tr><th>{t}Query{/t}</th><th>{t}Time [s]{/t}</th><th>{t}Count{/t}</th></tr>
{foreach $usage as $key => $item}
    <tr>
        <td>{$key}</td><td>{? echo round($item['time'] / 1000000, 3)}</td><td>{$item['count']}</td>
    </tr>
{/foreach}
</table>
</div>
