{extends @layout.phtml}

{block #title}{t}Commands{/t} (Mantra){/block}

{block #action} » {t}commands{/t}{/block}

{block #h2}{t}Commands{/t}{/block}

{block #help}{t}help:{/t} <a href='http://www.mongodb.org/display/DOCS/Commands'>{t}Commands{/t}</a>{/block}

{block #content}

<table cellspacing='0' class='data'>
<thead><tr>
    <th colspan='1'>{t}Name{/t}</th>
    <th><abbr title='{t}on admin database only{/t}'>A</abbr></th>
    <th><abbr title='{t}allowed on slave{/t}'>S</abbr></th>
    <th><abbr title='{t}read lock{/t}'>R</abbr></th>
    <th><abbr title='{t}write lock{/t}'>W</abbr></th>
    <th>{t}Help{/t}</th>
</tr></thead>
{foreach $commands as $name => $item}
<tr>
    <th>{$name}</th>
    <td>{? echo $item['adminOnly'] ? '&#10004;' : ''; }</td>
    <td>{? echo $item['slaveOk']   ? '&#10004;' : ''; }</td>
    <td>{? echo $item['lockType'] == -1 ? '&#10004;' : ''; }</td>
    <td>{? echo $item['lockType'] ==  1 ? '&#10004;' : ''; }</td>
    <td>{!$item['help']}</td>
</tr>
{/foreach}
</table>

<p>{t}A = on \'admin\' database only, S = allowed on slave, R = read lock, W = write lock{/t}</p>

