{extends @layout.phtml}

{block #title}{$presenter->database} {t}command{/t} (Mantra){/block}

{block #action} » {t}run command{/t}{/block}

{block #h2}{t}Run command{/t}{/block}

{block #help}{t}help:{/t} <a href='http://www.mongodb.org/display/DOCS/Commands'>{t}Commands{/t}</a>,
    <a href='http://www.mongodb.org/display/DOCS/Mongo+Extended+JSON'>{t}Extended JSON{/t}</a>{/block}

{block #content}

<p>
<a href='{plink Commands:default}'>{t}List commands{/t}</a>
</p>

{if isset($result)}<pre class='result'>{!$result}</pre><br>{/if}
{if isset($copy)}<pre class='result'>{!$copy}</pre>{/if}<br>

{control form}
