{extends @layout.phtml}

{block #title}{$presenter->database}.{$presenter->collection} » {t}create index{/t} (Mantra){/block}

{block #action} » {t}create index{/t}{/block}

{block #h2}{t}Create index{/t}{/block}

{block #help}{t}help:{/t} <a href='http://www.mongodb.org/display/DOCS/Indexes'>{t}Indexes{/t}</a>, 
    <a href='http://www.mongodb.org/display/DOCS/Optimization'>{t}Optimization{/t}</a>{/block}

{block #content}

{?$form->render('begin')}
{?$form->render('errors')}
<fieldset>
<table>
    <tr><td>{$form['name']->label}</td><td>{$form['name']->control}</td></tr>
{for $n = 0; $n < $count; $n++}
    <tr>
        <td>{$form['key'][$n]->label}</td>
        <td>
            {$form['key'][$n]->control} {$form['order'][$n]->control} {$form['order'][$n]->label}
        </td>
    </tr>
{/for}
    <tr><td></td><td>{$form['more']->control} {$form['less']->control}</td></tr>
    <tr><td></td><td>{$form['unique']->control} {$form['unique']->label}</td></tr>
    <tr><td></td><td>{$form['dropDups']->control} {$form['dropDups']->label}</td></tr>
    <tr><td></td><td>{$form['background']->control} {$form['background']->label}</td></tr>
    <tr><td></td><td>{$form['create']->control}</td></tr>
</table>
</fieldset>
{?$form->render('end')}
