{extends @layout.phtml}

{block #title}{$presenter->database} » create collection (mantra){/block}

{block #action} » create collection{/block}

{block #h2}Create collection{/block}

{block #help}help: <a href='http://www.mongodb.org/display/DOCS/Collections'>Collections</a>, 
    <a href='http://www.mongodb.org/display/DOCS/Capped+Collections'>Capped collections</a>{/block}

{block #content}

{control form}
