{extends @layout.phtml}

{block #title}{t}Databases{/t} (Mantra){/block}

{block #h2}{t}Select database{/t}{/block}

{block #help}{t}help:{/t} <a href='http://www.mongodb.org/display/DOCS/Manual'>{t}Manual{/t}</a>, 
    <a href='http://www.mongodb.org/display/DOCS/Databases'>{t}Databases{/t}</a>{/block}

{block #content}

<p>
<a href='{plink CreateDb:default}'>{t}Create database{/t}</a>
<a href='{plink Process:default}'>{t}Process list{/t}</a>
<a href='{plink Status:default}'>{t}Server status{/t}</a>
</p>

{if isset($version)}<p>MongoDB server: {!$version}; {t}PHP Mongo extension{/t}: <b>{? echo \Mongo::VERSION; }</b></p>{/if}

{var form => $presenter['form']}
{?$form->render('begin')}
{?$form->render('errors')}
<table cellspacing='0' class='data r3 r4 r5 r6'>
<colgroup span='2' /><colgroup span='4' align='right' />
<thead><tr><th></th><th>{t}Database{/t}</th><td>{t}Collections{/t}</td><td>{t}Objects{/t}</td><td>{t}Data size{/t}</td><td>{t}File size{/t}</td></tr></thead>
<tbody>
{foreach $databases as $db => $info}
    <tr>
        <td>{$form['db'][$info['id']]->control}</td>
        <td><b><a href='{plink Database:default, database=>$db}'>{$db}</a></b></td>
        <td>{$info['collections']}</td>
        <td>{$info['objects']}</td>
        <td>{$info['dataSize']|bytes:1}</td>
        <td>{$info['fileSize']|bytes:1}</td>
    </tr>
{/foreach}
</tbody>
</table>
<p>{$form['drop']->control}
<span class='minifieldset'>{$form['repair']->control} 
    {$form['backup']->control} {$form['backup']->label}
    <!--{ $form['preserve']->control} { $form['preserve']->label}--></span></p>
{?$form->render('end')}
