{extends @layout.phtml}

{block #title}{$presenter->database}.{$presenter->collection} select (mantra){/block}

{block #h2}Select items: {$presenter->collection}{/block}

{block #help}help: <a href='http://www.mongodb.org/display/DOCS/Querying'>Querying</a>,
    <a href='http://www.mongodb.org/display/DOCS/Mongo+Extended+JSON'>Extended JSON</a>{/block}
{block #content}

<p>
<a href='{plink Collection:default}'>Collection</a>
<a href='{plink Select:default}'>Select</a>
<a href='{plink Update:default}'>Update</a>
<a href='{plink Insert:default}'>Insert</a>
<a href='{plink Import:default}'>Import</a>
</p>

{control uploadForm}
{control localForm}
