{extends @layout.phtml}

{block #title}{$presenter->database}.{$presenter->collection} {t}insert{/t} (Mantra){/block}

{block #action} » {t}insert{/t}{/block}

{block #h2}{t}Insert item:{/t} {$presenter->collection}{/block}

{block #help}{t}help:{/t} <a href='http://www.mongodb.org/display/DOCS/Inserting'>{t}Inserting{/t}</a>,
    <a href='http://www.mongodb.org/display/DOCS/Mongo+Extended+JSON'>{t}Extended JSON{/t}</a>{/block}

{block #content}

<p>
<a href='{plink Collection:default}'>{t}Collection{/t}</a>
<a href='{plink Select:default}'>{t}Select{/t}</a>
<a href='{plink Update:default}'>{t}Update{/t}</a>
<a href='{plink Insert:default}'>{t}Insert{/t}</a>
<a href='{plink Import:default}'>{t}Import{/t}</a>
</p>

{control form}

