{extends @layout.phtml}

{block #title}{t}Processes{/t} (Mantra){/block}

{block #h2}{t}Processes{/t}{/block}

{block #help}{t}help:{/t} <a href='http://www.mongodb.org/display/DOCS/Viewing+and+Terminating+Current+Operation'>{t}Processes{/t}</a>{/block}

{block #content}


{var form => $presenter['form']}
{?$form->render('begin')}
{?$form->render('errors')}
<table cellspacing='0' class='data r2 r3 c4'>
<colgroup /><colgroup span='2' align='right' /><colgroup><col align='center' /></colgroup>
<tr><thead><th></th><th>{t}Process id{/t}</th><td>{t}Time{/t}</td><td>{t}Active{/t}</td><td>{t}Lock{/t}</td>
    <td>{t}Waiting{/t}</td><td>{t}Operation{/t}</td><td>{t}Namespace{/t}</td><td>{t}Query{/t}</td><td>{t}Client{/t}</td></thead></tr>
{foreach $processList as $process}
    <tr>
        <td>{$form['process'][$process['opid']]->control}</td>
        <td>{$process['opid']}</td>
        <td>{$process['secs_running']}s</td>
        <td>{? echo $process['active'] ? 'yes' : 'no'}</td>
        <td>{$process['lockType']}</td>
        <td>{? echo $process['waitingForLock'] ? 'yes' : 'no'}</td>
        <td>{$process['op']}</td>
        <td>{$process['ns']}</td>
        <td>{!$process['query']}</td>
        <td>{$process['client']}</td>
    </tr>
{/foreach}
</table>
{$form['kill']->control}
{?$form->render('end')}
