{extends @layout.phtml}

{block #title}{t}Server status{/t} (Mantra){/block}

{block #action} » {t}server status{/t}{/block}

{block #h2}{t}Server status{/t}{/block}

{block #help}{t}help:{/t} <a href='http://www.mongodb.org/display/DOCS/Monitoring+and+Diagnostics'>{t}Diagnostics{/t}</a>,
    <a href='http://www.mongodb.org/display/DOCS/Optimization'>{t}Optimization{/t}</a>,
    <a href='http://www.mongodb.org/display/DOCS/Command+Line+Parameters'>{t}Configuration{/t}</a>{/block}

{block #content}

<p>
<a href='{plink Status:default}'>{t}Server status{/t}</a>
<a href='{plink Usage:default}'>{t}Collection usage{/t}</a>
<a href='http://{$firstServer}:28017/'>{t}Server dignostic screen{/t}</a>
</p>

<p>
MongoDB server: {!$version}<br>
{t}running as:{/t} <b>{$masterSlave}</b><br>
{t}configuration:{/t} <b>{$cmdLine}</b><br>
</p>

{var form => $presenter['form']}
{?$form->render('begin')}
{?$form->render('errors')}
<p>{$form['shutdown']->control}</p>
<!--<fieldset>
    { $form['lock']->control}
    { $form['unlock']->control}
</fieldset>-->
{?$form->render('end')}

<br>
<table cellspacing='0' class='info'>
{foreach $status as $key => $item}
    <tr>
    {if is_array($item)}
        <th colspan='2'>{$key}</th></tr>
        {foreach $item as $subkey => $subitem}
            <tr><th>{$subkey}</th><td>
            {if is_array($subitem)}
                {foreach $subitem as $subsubkey => $subsubitem}
                    {$subsubkey}: {$subsubitem}<br>
                {/foreach}
            {else}
                {$subitem}
            {/if}
            </td></tr>
        {/foreach}
    {else}
        <th>{$key}</th><td>{$item}</td>
    {/if}
    </tr>
{/foreach}
</table>

