{extends @layout.phtml}

{block #title}{$presenter->database}.{$presenter->collection} update (mantra){/block}

{block #action} » update{/block}

{block #h2}Update items: {$presenter->collection}{/block}

{block #help}help: <a href='http://www.mongodb.org/display/DOCS/Updating'>Updating</a>, 
    <a href='http://www.mongodb.org/display/DOCS/Removing'>Removing</a>,
    <a href='http://www.mongodb.org/display/DOCS/Mongo+Extended+JSON'>Extended JSON</a>{/block}

{block #content}

<p>
<a href='{plink Collection:default}'>Collection</a>
<a href='{plink Select:default}'>Select</a>
<a href='{plink Update:default}'>Update</a>
<a href='{plink Insert:default}'>Insert</a>
</p>

{control form}

<div class='note'>
<h4>Update operators:</h4>
<ul>
<li><code>$inc</code> - increment value by given number
<li><code>$set</code> - set new value
<li><code>$unset</code> - unset key
</ul>
<ul>
<li><code>$push</code> - append item to array
<li><code>$pushAll</code> - append more items to array
<li><code>$addToSet</code> - add item to set (duplicates are not inserted)
<li><code>$pop</code> - remove last (1) or first (-1) item from array
<li><code>$pull</code> - remove all occurences of given value from array
<li><code>$pullAll</code> - remove all occurences of all given values from array
</ul>
</div>

<script>
/*    $(document).ready(function() {
        if ($('#frmform-delete:checked').get()) {
            $('table tr:nth-child(3)').hide();
        }
        $('#frmform-delete').change(function() {
            alert($('#frmform-delete:checked'.get()));
            if ($('#frmform-delete:checked'.get())) {
                $('table tr:nth-child(3)').hide();
            } else {
                $('table tr:nth-child(3)').show();
            }
        });
    });*/
</script>
