{extends @layout.phtml}

{block #title}{$presenter->database}.{$presenter->collection} {t}update{/t} (Mantra){/block}

{block #action} » {t}update{/t}{/block}

{block #h2}{t}Update items:{/t} {$presenter->collection}{/block}

{block #help}{t}help:{/t} <a href='http://www.mongodb.org/display/DOCS/Updating'>{t}Updating{/t}</a>, 
    <a href='http://www.mongodb.org/display/DOCS/Removing'>{t}Removing{/t}</a>,
    <a href='http://www.mongodb.org/display/DOCS/Mongo+Extended+JSON'>{t}Extended JSON{/t}</a>{/block}

{block #content}

<p>
<a href='{plink Collection:default}'>{t}Collection{/t}</a>
<a href='{plink Select:default}'>{t}Select{/t}</a>
<a href='{plink Update:default}'>{t}Update{/t}</a>
<a href='{plink Insert:default}'>{t}Insert{/t}</a>
<a href='{plink Import:default}'>{t}Import{/t}</a>
</p>

{control form}

<div class='note'>
<h4>{t}Update operators:{/t}</h4>
<ul>
<li><code>$inc</code> - increment value by given number
<li><code>$set</code> - set new value
<li><code>$unset</code> - unset key
</ul>
<ul>
<li><code>$push</code> - append item to array
<li><code>$pushAll</code> - append more items to array
<li><code>$addToSet</code> - add item to set (duplicates are not inserted)
<li><code>$pop</code> - remove last (1) or first (-1) item from array
<li><code>$pull</code> - remove all occurences of given value from array
<li><code>$pullAll</code> - remove all occurences of all given values from array
</ul>
</div>
