{extends @layout.phtml}

{block #title}{t}Collection usage{/t} (Mantra){/block}

{block #action} » {t}collection usage{/t}{/block}

{block #h2}{t}Collection usage{/t}{/block}

{block #help}{t}help:{/t} <a href='http://www.mongodb.org/display/DOCS/Optimization'>{t}Optimization{/t}</a>{/block}

{block #content}

<table cellspacing='0' class='info r2 r3'>
<colgroup /><colgroup span='2' align='right' />
{foreach $usage as $key => $item}
    <tr>
    {if is_array($item)}
        <th colspan='1'>{$key}</th><th colspan='1'>{t}time [s]{/t}</th><th colspan='1'>{t}queries{/t}</th></tr>
        {foreach $item as $subkey => $subitem}
            <tr><td>{$subkey}</td><td>{? echo round($subitem['time'] / 1000000, 3)}</td><td>{$subitem['count']}</td></tr>
        {/foreach}
    {else}
        <th>{$key}</th><td>{$item}</td>
    {/if}
    </tr>
{/foreach}
</table>

